# Development overrides for docker-compose.yml
services:
  backend:
    build:
      target: php-backend  # Use PHP for now, switch to node-backend later
    volumes:
      - ./backend:/app:delegated
      - /app/vendor  # Exclude vendor directory
      - /app/node_modules  # Exclude node_modules
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - PHP_IDE_CONFIG=serverName=ft_transcendence
    command: php-fpm -F  # Run in foreground for better logging

  frontend:
    build:
      target: development
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules  # Exclude node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    ports:
      - "5173:5173"  # Expose Vite dev server directly for HMR

  nginx:
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx

  database:
    volumes:
      - ./backups:/backups  # Mount backup directory
    environment:
      - SQLITE_DEBUG=1