# Generated by Django 5.1.5 on 2026-01-23 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pet',
            new_name='pets_user_id_6daacf_idx',
            old_name='pet_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='pet',
            new_name='pets_species_a3549a_idx',
            old_name='pet_species_idx',
        ),
        migrations.RenameIndex(
            model_name='petanalysis',
            new_name='pet_analyse_pet_id_b12b89_idx',
            old_name='petanalysis_pet_created_idx',
        ),
        migrations.RenameIndex(
            model_name='petanalysis',
            new_name='pet_analyse_user_id_fd2abf_idx',
            old_name='petanalysis_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_user_id_fbe33d_idx',
            old_name='userprofile_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_created_26443b_idx',
            old_name='userprofile_created_idx',
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
