# Generated by Django 5.1.5 on 2026-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
